const DOMAIN = "searchadder.pages.dev";

export function onRequest(context) {
  const params = context.params.catchall;
  if (params.length != 3 || params[2] != "opensearch.xml") {
    return new errorResponse(`Bad path ${params}`)
  }

  let name = decodeURIComponent(params[0])
  let searchUrl = decodeURIComponent(params[1])
  
  searchUrl = searchUrl
    .replaceAll("{", "%7B")
    .replaceAll("}", "%7D")
    .replaceAll("%s", "{searchTerms}")

  return new Response(`\
<OpenSearchDescription
  xmlns="http://a9.com/-/spec/opensearch/1.1/"
  xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>${escapeXML(name)}</ShortName>
  <Description>Generated by ${DOMAIN}</Description>
  <Image width="16" height="16" type="image/x-icon">https://${DOMAIN}/favicon.ico</Image>
  <Url type="text/html" template="${escapeXML(searchUrl)}"/>
</OpenSearchDescription>
`, {"headers": {"Content-Type": "application/xml"}});
// </OpenSearchDescription>`, {"headers": {"Content-Type": "application/opensearchdescription+xml"}});
}


/**
 * 
 * @param {string} msg The name of the missing parameter
 */
function errorResponse(msg) {
  return new Response(msg, {status: 400})
}

/**
 * 
 * @param {string} str The string to escape
 * @returns Fully XML-escaped string
 */
function escapeXML(str) {
  return str
    .replace("&", "&amp;")
    .replace("<", "&lt;")
    .replace(">", "&gt")
    .replace('"', "&#34;")
    .replace("'", "&#39;");
}