const DOMAIN = "searchadder.pages.dev";

export default {
    async fetch(request: Request): Promise<Response> {
        let url;
        try {
            url = new URL(request.url);
        } catch (e) {
            return new Response("Invalid URL", { status: 400 });
        }
        switch (url.pathname) {
            case "/opensearch.xml":
                const name = url.searchParams.get("name");
                const searchUrl = url.searchParams.get("url");

                if (!name) return new Response(`Missing search parameter "name"`, { status: 400 });
                if (!searchUrl) return new Response(`Missing search parameter "url"`, { status: 400 });

                return new OpenSearchResponse(name, searchUrl);

            default:
                return new Response("Not Found", { status: 404 });
        }
    }
};

class OpenSearchResponse extends Response {
    constructor(name: string, url: string) {
        const transformedUrl = url
            .replaceAll("{", "%7B")
            .replaceAll("}", "%7D")
            .replaceAll("%s", "{searchTerms}");

        super(`\
<OpenSearchDescription
  xmlns="http://a9.com/-/spec/opensearch/1.1/"
  xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>${escapeXML(name)}</ShortName>
  <Description>Generated by ${DOMAIN}</Description>
  <Image width="16" height="16" type="image/x-icon">https://${DOMAIN}/favicon.ico</Image>
  <Url type="text/html" template="${escapeXML(transformedUrl)}"/>
</OpenSearchDescription>
`, { "headers": { "Content-Type": "application/xml" } });
    }
}

function escapeXML(str: string): string {
    return str
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt")
        .replace('"', "&#34;")
        .replace("'", "&#39;");
}